### ISSUE TITLE
Create a Basic React Project

### ISSUE THREAD

**Issue by jayeshkattar** [GirlScriptSummerOfCode/Kranti#1]
Create a Project (Similar to Hello world).

**Comment by adi44** [comment]
I would like to work on this issue

**Comment by devesh-verma** [comment]
hey @adi44 as the discussion happened in the channel angular is not yet confirmed.

**Comment by adi44** [comment]
I will work

**Comment by sourabhpruthi10** [comment]
Hey i would like to work on this issue

**Comment by lalitmee** [comment]
Hey @adi44, you are assigned to this issue and you have the time of 24 hours to complete this. 

Please don't take the deadline in a wrong way, it's only for managing the project easily and in a good way. :innocent:

**Comment by devesh-verma** [comment]
@lalitmee hey if he doesn't finish it by tomorrow morning plz do assign it to me.
Actually this was supposed to be assigned to me as I was in discussion with avani regarding angular or react. And because of that I did not comment on the issue. 
I request if he doesn't complete it by tomorrow morning plz assign it to me.

**Comment by lalitmee** [comment]
@devshiva619, sorry for not assigning you. :innocent: 
Actually, I was not aware of your discussion with @AvaniVerma. But next time if you want to get assigned to some issue, please comment on that issue. :+1: 
And yeah, don't worry you will get a lot of issues to work on. This is the simple one and if @adi44 will not be able to do it by the deadline, you will be assigned to the issue.

**Comment by ayush221b** [comment]
Hello, can I work on this right now? This is a very basic step and can be completed in a very less amount of time.

**Comment by AvaniVerma** [comment]
Hey @ayush221b  , the issue has been already assigned to someone else. However, I request you to keep an eye on the repo for new issues.

**Comment by adi44** [comment]
I will do this task by tonight since I saw discussion today 
sorry for delay

@jayeshkattar @AvaniVerma @lalitmee

**Comment by lalitmee** [comment]
Hey @adi44, I think its very easy. So if you can complete it by tonight at 11 PM, it would be great. :+1:

**Comment by adi44** [comment]
sure @lalitmee 
I will do it
