### ISSUE TITLE
Create Tabs

### ISSUE THREAD

**Issue by jayeshkattar** [GirlScriptSummerOfCode/Kranti#3]
Homepage 
Meet the Revolutionaries 
Support
FAQs
Press
Contact
Blog

Content Here: https://drive.google.com/drive/folders/0BwpCIeAR0xFcTVlXc1FvQXZvcHM?usp=sharing

**Comment by akansha006** [comment]
I would like to work on this issue.

**Comment by adi44** [comment]
I would like to work on this Issue

**Comment by MadhavBahl** [comment]
Tell me if I can work on this one :)

**Comment by EspanX** [comment]
I am interested to work on this issue

**Comment by siddhishree** [comment]
I would like to work on this issue. We can divide up the work.

**Comment by Pallavi024** [comment]
Even I would also love to work on this issue :smile:

**Comment by ayush221b** [comment]
I would also like to work on this issue. In fact would it possible if we divide the tabs among all those interested?

**Comment by roygrv21** [comment]
Hey even I would like to work on this issue

**Comment by AvaniVerma** [comment]
Since it's first come, first assigned, I request @akansha006 to work on this issue. I also want you to complete the issue within the next 4-5 days, failing which the issue will be assigned to someone else. As of now, you only have to create the tabs which should be responsive

**Comment by AvaniVerma** [comment]
@akansha006 If you could please reply a yes or no, we'll know that you've seen it. If you fail to do so by 10PM tonight we'll assign it to someone else.

**Comment by AvaniVerma** [comment]
@MadhavBahlMD Would you like to work on this issue now ? Please respond soon.

**Comment by amritsrivastava** [comment]
Hey, I would like to work on this issue.

**Comment by AvaniVerma** [comment]
@amritsrivastava Please go ahead.

**Comment by AvaniVerma** [comment]
@amritsrivastava Sure. Go ahead.

**Comment by amritsrivastava** [comment]
Okay

**Comment by shreyateeza** [comment]
@AvaniVerma @jayeshkattar Is this issue up for grabs? I would like to work on it.

**Comment by muskan21jain** [comment]
@AvaniVerma I want to work on this issue. Can I?

**Comment by adi44** [comment]
I want to work on this issue @AvaniVerma

**Comment by vaarigupta** [comment]
Is this issue still available to work ? I would **like to work** upon this. @AvaniVerma

**Comment by lalitmee** [comment]
@All, Guys this issue is having a PR and we are reviewing it. So if you want to contribute to this issue you can review that PR and give your suggestions as comments. :+1:

**Comment by AvaniVerma** [comment]
@shreyateeza @94151 @adi44 @vaarigupta Thanks for your interest. As of now we already have a PR but like @lalitmee mentioned you can provide your suggestions as comments. It'll be highly appreciated and points will be awarded for the same.

**Comment by vaarigupta** [comment]
okkk sure @AvaniVerma  but one thing I wanna ask that I have forked the repo and there is not any  changes in the index.html file ?

**Comment by AvaniVerma** [comment]
As of now, we haven't merged any requests so you'll have to read code from the PR.

**Comment by vaarigupta** [comment]
@jayeshkattar  I m working on meet the revolutionary page right now . I will create a PR by tom
