### ISSUE TITLE
Design SVG logo for the website

### ISSUE THREAD

**Issue by AvaniVerma** [GirlScriptSummerOfCode/Kranti#8]
**_Anyone can work on this issue._**

**The final logo will be chosen in the end. Till then, please keep contributing.**
Points will be awarded for every contributor's efforts.

The logo must align with the idea of Kranti, i.e, providing opportunities to socially disadvantaged young women in order to empower them.

**Comment by shreyateeza** [comment]
Working on this issue!

**Comment by shreyateeza** [comment]
@AvaniVerma  Please provide some description of what needs to be kept in mind while designing the logo.

**Comment by shreyateeza** [comment]
Logo 1 -
![two](https://user-images.githubusercontent.com/30488330/42147099-c979da68-7de9-11e8-8d2b-790f89cf3108.png)

Logo 2 -
![five](https://user-images.githubusercontent.com/30488330/42147107-d9a4e888-7de9-11e8-85c8-3ce55bb76349.png)

@AvaniVerma  @troublemagnet  How about these logo samples?

**Comment by troublemagnet** [comment]
@shreyateeza Good job. 
Couple of things - 
1) Whenever you want a review, create a PR. 
2) quick question - how did you come up with these?

PS - make a PR, we can discuss why or why should not we go with these samples.

**Comment by shreyateeza** [comment]
@troublemagnet  PR #10  created! I hope this PR answers your query 2.

**Comment by AvaniVerma** [comment]
@shreyateeza This logo looks great. Amazing work. I like how you have created a logo that respects their color choice.
 
As far as I know, Kranti team has no web presence as of now, so they most probably have no logo as well. I'd like to know how did you come up with the idea for this logo.
However, I'd like you to design a logo that aligns with the idea of Kranti, i.e, providing opportunities to socially disadvantaged young women in order to empower them.

**Comment by adi44** [comment]
hello
i am graphic designer so I would like to work for logo m

**Comment by AvaniVerma** [comment]
@adi44 Sure. Go ahead. Please see my previous comments regarding what is expected.

**Comment by adi44** [comment]
![kranti](https://user-images.githubusercontent.com/31381639/42233244-9e2139ee-7f0e-11e8-8d46-32041f8462c6.png)
@AvaniVerma

**Comment by saberprashant** [comment]
Hi @AvaniVerma , can I also submit a PR for this issue, as I have a good idea for a logo?

**Comment by lalitmee** [comment]
Yeah @saberprashant, you can create PR. :+1: 
Don't ask for creating PR :innocent: we will review it and then if we find it useful we will merge it.

**Comment by saberprashant** [comment]
Thanks @lalitmee

**Comment by saberprashant** [comment]
Hi @AvaniVerma @lalitmee @troublemagnet , I've submitted a PR for this issue, please review it. :)
Thanks!
